from dll import *
dl=Dll()
dl.append(10)
dl.append(12)
dl.append(4)
dl.append(8)
dl.traverse()
dl.insert(10,25)
dl.traverse()
dl.delete(4)
dl.traverse()
dl.reverse()
dl.traverse()
print(dl.head.val)
